ALTER TABLE "Question" ADD COLUMN "points" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Submission" ADD COLUMN "gradedAt" TIMESTAMP(3);
ALTER TABLE "Submission" ADD COLUMN "totalScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Answer" ADD COLUMN "isCorrect" BOOLEAN;
ALTER TABLE "Answer" ADD COLUMN "pointsAwarded" INTEGER;
